version: '3.8'

services:
  app:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5433/aifeed
      - NODE_ENV=development
    depends_on:
      - db

  db:
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=aifeed
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 